parameters:
    fsc.email_filter.validator.class: FSC\EmailFilterBundle\Validator\EmailValidator

services:
    fsc.email_filter.validator:
        class: %fsc.email_filter.validator.class%
        arguments: [%fsc.email_filter.validator.file%]
        tags:
            - { name: validator.constraint_validator, alias: fsc.email_filter.validator }
